import { ServicePageData, ServiceFeature, RelatedLink } from './service-pages.data';

const SUBJECT_FEATURES: ServiceFeature[] = [
  { icon: '🎓', title: 'Degree-Qualified Experts', desc: 'Every subject is matched to a specialist with a relevant degree and a track record in that exact field.' },
  { icon: '📝', title: 'Original, Cited Work', desc: 'All work is written from scratch, checked for originality, and referenced in your required citation style.' },
  { icon: '🔒', title: '100% Confidential', desc: 'Your identity stays encrypted and your details are never shared. Credentials are deleted within 48 hours.' },
  { icon: '💳', title: 'Flexible Installments', desc: 'Stripe-secured pay-as-you-go — you only pay as work is delivered and admin-reviewed.' },
  { icon: '🔄', title: 'Unlimited Revisions', desc: 'Unlimited revisions within 7 days until the work meets your standard — at no extra cost.' },
  { icon: '📞', title: '24/7 Live Support', desc: 'Real humans reply in under 5 minutes on WhatsApp, any timezone, every day.' },
];

const SUBJECT_LINKS: RelatedLink[] = [
  { label: 'Mathematics Help', path: '/mathematics-help' },
  { label: 'Statistics Help', path: '/statistics-help' },
  { label: 'Accounting Help', path: '/accounting-help' },
  { label: 'Finance Help', path: '/finance-help' },
  { label: 'Economics Help', path: '/economics-help' },
  { label: 'Nursing Help', path: '/nursing-help' },
  { label: 'Computer Science Help', path: '/computer-science-help' },
  { label: 'Biology Help', path: '/biology-help' },
  { label: 'Chemistry Help', path: '/chemistry-help' },
  { label: 'Physics Help', path: '/physics-help' },
  { label: 'Psychology Help', path: '/psychology-help' },
  { label: 'Business Management Help', path: '/business-management-help' },
  { label: 'Marketing Help', path: '/marketing-help' },
  { label: 'English Help', path: '/english-help' },
  { label: 'Law Help', path: '/law-help' },
];

const CORE_LINKS: RelatedLink[] = [
  { label: 'Online Class Help', path: '/online-class-help' },
  { label: 'Assignment Help', path: '/assignment-help' },
  { label: 'Online Exam Help', path: '/exam-help' },
];

function subjectRelated(slug: string): RelatedLink[] {
  const siblings = SUBJECT_LINKS.filter(l => l.path !== `/${slug}`).slice(0, 4);
  return [...siblings, ...CORE_LINKS.slice(0, 2)];
}

function makeSubject(
  slug: string, subject: string, kw: string,
  heroLead: string, introParas: string[],
  topics: string[], faqs: { q: string; a: string }[]
): ServicePageData {
  return {
    slug,
    title: `${subject} Help | Expert ${subject} Assignment & Class Help`,
    metaDescription: `Professional ${subject} help from degree-qualified experts. We handle ${subject} assignments, homework, quizzes & exams — original work, delivered on time. Pay weekly, 99.1% success rate.`,
    keywords: `${subject.toLowerCase()} help, ${subject.toLowerCase()} assignment help, do my ${subject.toLowerCase()} homework, ${kw}, online ${subject.toLowerCase()} help`,
    badge: `${subject} Help`,
    h1: `${subject} Help From Degree-Qualified Experts`,
    heroLead,
    introH2: `Reliable ${subject} Help for Every Assignment`,
    introParas: [
      ...introParas,
      `Our ${subject.toLowerCase()} experts regularly handle ${topics.join(', ')} — matched to your rubric and delivered before every deadline.`,
    ],
    featuresH2: `Why Students Choose Our ${subject} Help`,
    features: SUBJECT_FEATURES,
    processH2: `How to Get ${subject} Help`,
    steps: [
      { num: '01', title: 'Share the Details', desc: `Send your ${subject.toLowerCase()} assignment, class access, or problem set with the deadline — reviewed free.` },
      { num: '02', title: 'Approve the Quote', desc: 'Get a transparent price with a flexible weekly payment plan before any work begins.' },
      { num: '03', title: 'Expert Completes It', desc: `A ${subject.toLowerCase()} specialist completes the work, then our quality team reviews it end to end.` },
      { num: '04', title: 'Review & Revise', desc: 'Download your work ahead of the deadline with unlimited revisions within 7 days.' },
    ],
    faqs,
    related: subjectRelated(slug),
    ctaH2: `Get Expert ${subject} Help Today`,
    ctaText: `Get a free, no-obligation quote in 60 seconds and see how affordable dependable ${subject.toLowerCase()} help can be.`,
  };
}

export const SUBJECT_PAGES: Record<string, ServicePageData> = {
  'mathematics-help': makeSubject('mathematics-help', 'Mathematics', 'math homework help, do my math class, calculus help',
    'Struggling with calculus, algebra, or a full math course? Our degree-qualified math experts solve problems with clear working and complete your entire math class accurately and on time.',
    ['Mathematics builds on itself, so one missed week can snowball fast. EduPilotHelp connects you with math specialists who deliver correct, clearly worked solutions across every level.',
     'From single problem sets to full online math courses in MyMathLab, ALEKS, or WebAssign, your expert shows proper methods and meets every deadline.'],
    ['calculus', 'linear algebra', 'differential equations', 'discrete math', 'statistics problem sets'],
    [{ q: 'Can you do my whole math class?', a: 'Yes. A math expert completes homework, quizzes, and exams across your entire course in platforms like MyMathLab, ALEKS, and WebAssign.' },
     { q: 'Do I get step-by-step working?', a: 'When you need it, yes — fully worked solutions so you can follow the method, not just the final answer.' },
     { q: 'Which math topics do you cover?', a: 'Algebra, calculus, linear algebra, differential equations, discrete math, and statistics at all levels.' },
     { q: 'How much does math help cost?', a: 'Pricing depends on level and volume, with flexible weekly installments. Request a free quote for an exact price.' }]),
  'statistics-help': makeSubject('statistics-help', 'Statistics', 'stats homework help, do my statistics class, spss help',
    'Statistics coursework — from hypothesis testing to regression in SPSS or R — handled by expert statisticians who deliver accurate analysis and clear interpretation, on time.',
    ['Statistics blends math with software and interpretation, which trips up many students. EduPilotHelp provides statistics help from experts fluent in SPSS, R, Excel, and StatCrunch.',
     'Your expert completes problem sets, data analysis projects, and timed quizzes, showing correct methods and readable interpretations of every result.'],
    ['hypothesis testing', 'regression analysis', 'ANOVA', 'probability', 'SPSS and R projects'],
    [{ q: 'Can you do statistics work in SPSS or R?', a: 'Yes. Our experts complete analyses in SPSS, R, Excel, StatCrunch, and Minitab with correct output and clear interpretation.' },
     { q: 'Do you handle full statistics classes?', a: 'Yes — homework, data projects, quizzes, and exams across your entire statistics course.' },
     { q: 'Can you explain the results?', a: 'Yes, we can include plain-language interpretation of every test so the analysis makes sense.' },
     { q: 'Is my data kept private?', a: 'Completely. Your data and identity are encrypted and never shared, and access is deleted within 48 hours.' }]),
  'accounting-help': makeSubject('accounting-help', 'Accounting', 'accounting homework help, do my accounting class, mylab accounting help',
    'From journal entries to full financial statements, our CPA-level experts complete your accounting homework, projects, and exams accurately and before every deadline.',
    ['Accounting demands precision — one wrong figure cascades through the statements. EduPilotHelp gives you accounting help from experts who work in MyAccountingLab, Connect, and WileyPLUS daily.',
     'Your expert completes journal entries, ledgers, financial statements, and cost analyses with accurate figures and correct treatment, quality-checked before submission.'],
    ['financial accounting', 'managerial accounting', 'cost accounting', 'auditing', 'tax problem sets'],
    [{ q: 'Can you do my MyAccountingLab or Connect homework?', a: 'Yes. Our experts complete accounting homework, quizzes, and exams directly in MyAccountingLab, McGraw Hill Connect, and WileyPLUS.' },
     { q: 'Which accounting courses do you cover?', a: 'Financial, managerial, cost, and intermediate accounting, plus auditing and tax.' },
     { q: 'Are the figures accurate?', a: 'Yes — every submission is verified by our quality team before delivery.' },
     { q: 'Can you handle a full accounting class?', a: 'Yes, from weekly homework to the final exam, to your target grade.' }]),
  'finance-help': makeSubject('finance-help', 'Finance', 'finance homework help, do my finance class, corporate finance help',
    'Corporate finance, valuation, and financial modeling handled by finance experts who deliver accurate calculations and clear analysis across your entire course.',
    ['Finance combines formulas, spreadsheets, and judgment. EduPilotHelp provides finance help from experts who complete valuations, NPV/IRR analyses, and financial models accurately.',
     'Your expert handles finance homework, Excel modeling, and timed exams, showing correct methods and clean, defensible outputs.'],
    ['time value of money', 'capital budgeting', 'portfolio theory', 'financial modeling', 'risk analysis'],
    [{ q: 'Can you build financial models in Excel?', a: 'Yes. Our experts build valuation models, DCF analyses, and financial projections in Excel with correct formulas and clear structure.' },
     { q: 'Which finance topics do you cover?', a: 'Corporate finance, investments, capital budgeting, portfolio theory, and risk management.' },
     { q: 'Do you handle timed finance exams?', a: 'Yes, timed exams are completed in real time by an expert ready during your exam window.' },
     { q: 'Is it confidential?', a: 'Fully. Your identity and details are encrypted and deleted within 48 hours of completion.' }]),
  'economics-help': makeSubject('economics-help', 'Economics', 'economics homework help, do my economics class, micro macro econ help',
    'Micro, macro, and econometrics coursework completed by economics experts with clear graphs, correct models, and well-argued analysis — delivered on time.',
    ['Economics mixes theory, graphs, and math that can overwhelm a busy schedule. EduPilotHelp provides economics help from experts across micro, macro, and econometrics.',
     'Your expert completes problem sets, graph-based questions, and essays with correct models and clear reasoning, quality-checked before submission.'],
    ['microeconomics', 'macroeconomics', 'econometrics', 'game theory', 'supply and demand analysis'],
    [{ q: 'Can you handle econometrics with software?', a: 'Yes. Our experts complete econometrics work in Stata, R, and EViews with correct output and interpretation.' },
     { q: 'Which economics courses do you cover?', a: 'Microeconomics, macroeconomics, econometrics, international economics, and game theory.' },
     { q: 'Can you draw the required graphs?', a: 'Yes, we produce accurate, properly labeled economic graphs for any assignment.' },
     { q: 'Can you take my whole econ class?', a: 'Yes, from weekly problem sets to the final exam.' }]),
  'nursing-help': makeSubject('nursing-help', 'Nursing', 'nursing homework help, do my nursing class, nursing care plan help',
    'From care plans to evidence-based papers, our nursing experts — many with clinical backgrounds — complete your nursing coursework accurately, confidentially, and on time.',
    ['Nursing programs are intense, blending clinical knowledge with heavy writing and strict rubrics. EduPilotHelp provides nursing help from experts who understand care plans, NCLEX-style questions, and APA formatting.',
     'Your expert completes care plans, evidence-based practice papers, discussion posts, and quizzes to your rubric, quality-reviewed before submission.'],
    ['care plans', 'evidence-based practice papers', 'pathophysiology', 'pharmacology', 'NCLEX-style questions'],
    [{ q: 'Can you write nursing care plans?', a: 'Yes. Our nursing experts write complete, rubric-matched care plans with correct nursing diagnoses and interventions.' },
     { q: 'Do you follow APA format?', a: 'Yes, all nursing papers are formatted in APA 7th edition with proper citations and references.' },
     { q: 'Which nursing courses do you cover?', a: 'Pathophysiology, pharmacology, health assessment, community health, and evidence-based practice.' },
     { q: 'Is my information confidential?', a: 'Absolutely — your identity is encrypted, never shared, and access is deleted within 48 hours.' }]),
  'computer-science-help': makeSubject('computer-science-help', 'Computer Science', 'programming help, do my coding assignment, cs homework help',
    'Coding assignments, data structures, and full CS courses handled by developer-experts who deliver clean, tested, well-commented code that passes autograders.',
    ['Computer science is unforgiving — code either works or it does not. EduPilotHelp provides CS help from working developers across Python, Java, C++, JavaScript, and SQL.',
     'Your expert completes programming labs, algorithms, and projects with clean, tested, well-commented code, verified against autograders before submission.'],
    ['data structures and algorithms', 'Python and Java projects', 'SQL and databases', 'web development', 'operating systems labs'],
    [{ q: 'Which programming languages do you cover?', a: 'Python, Java, C, C++, JavaScript, SQL, R, and more, plus frameworks and databases.' },
     { q: 'Will the code pass autograders?', a: 'Yes. Our experts test against autograders and include comments so you can follow the logic.' },
     { q: 'Can you do a full CS course?', a: 'Yes, from weekly labs to final projects and exams across your entire course.' },
     { q: 'Is my work original?', a: 'Yes — all code is written from scratch for you and checked for originality.' }]),
  'biology-help': makeSubject('biology-help', 'Biology', 'biology homework help, do my biology class, anatomy help',
    'From cell biology to anatomy and lab reports, our biology experts complete your coursework, quizzes, and exams with accurate science and clear writing.',
    ['Biology spans dense concepts, diagrams, and lab work across a demanding semester. EduPilotHelp provides biology help from science experts who deliver accurate, well-organized work.',
     'Your expert completes readings, lab reports, quizzes, and exams in Mastering Biology and other platforms, quality-checked for scientific accuracy.'],
    ['cell biology', 'genetics', 'anatomy and physiology', 'microbiology', 'lab reports'],
    [{ q: 'Can you write biology lab reports?', a: 'Yes. Our experts write complete lab reports with correct structure, data analysis, and scientific writing.' },
     { q: 'Do you work in Mastering Biology?', a: 'Yes, we complete assignments, quizzes, and tests directly in Mastering Biology and similar platforms.' },
     { q: 'Which biology courses do you cover?', a: 'Cell biology, genetics, anatomy and physiology, microbiology, and ecology.' },
     { q: 'Can you handle a full biology class?', a: 'Yes, from weekly work to the final exam, to your target grade.' }]),
  'chemistry-help': makeSubject('chemistry-help', 'Chemistry', 'chemistry homework help, do my chemistry class, organic chemistry help',
    'Organic, general, and analytical chemistry handled by chemistry experts who balance equations, solve mechanisms, and complete lab reports accurately and on time.',
    ['Chemistry combines abstract concepts with precise calculations and mechanisms. EduPilotHelp provides chemistry help from experts across general, organic, and analytical chemistry.',
     'Your expert completes problem sets, mechanisms, and lab reports in ALEKS, Mastering Chemistry, and OWLv2, verified for accuracy before submission.'],
    ['general chemistry', 'organic chemistry mechanisms', 'stoichiometry', 'thermodynamics', 'lab reports'],
    [{ q: 'Can you do organic chemistry mechanisms?', a: 'Yes. Our chemistry experts solve reaction mechanisms, synthesis problems, and structure questions accurately.' },
     { q: 'Do you work in ALEKS or Mastering Chemistry?', a: 'Yes, we complete assignments and tests directly in ALEKS, Mastering Chemistry, and OWLv2.' },
     { q: 'Which chemistry courses do you cover?', a: 'General, organic, analytical, physical, and biochemistry.' },
     { q: 'Can you write chemistry lab reports?', a: 'Yes, with correct calculations, data analysis, and proper scientific format.' }]),
  'physics-help': makeSubject('physics-help', 'Physics', 'physics homework help, do my physics class, mechanics help',
    'From mechanics to electromagnetism, our physics experts solve problems with clear working and complete your physics coursework and exams accurately, on time.',
    ['Physics rewards precise problem-solving that takes time most students do not have. EduPilotHelp provides physics help from experts across mechanics, E&M, and modern physics.',
     'Your expert completes problem sets and exams in WebAssign, Mastering Physics, and other platforms, showing correct methods and units throughout.'],
    ['classical mechanics', 'electromagnetism', 'thermodynamics', 'waves and optics', 'modern physics'],
    [{ q: 'Do you work in WebAssign or Mastering Physics?', a: 'Yes. Our experts complete physics homework and tests directly in WebAssign, Mastering Physics, and similar platforms.' },
     { q: 'Do I get worked solutions?', a: 'When you need it, yes — full step-by-step working with correct units and methods.' },
     { q: 'Which physics courses do you cover?', a: 'Classical mechanics, electromagnetism, thermodynamics, optics, and modern physics.' },
     { q: 'Can you handle timed physics exams?', a: 'Yes, timed exams are completed in real time by an expert ready during your exam window.' }]),
  'psychology-help': makeSubject('psychology-help', 'Psychology', 'psychology homework help, do my psychology class, apa paper help',
    'Research papers, statistics, and discussion posts across psychology courses, written by psychology experts in correct APA format and delivered on time.',
    ['Psychology blends theory, research methods, and heavy APA writing. EduPilotHelp provides psychology help from experts across developmental, cognitive, abnormal, and social psychology.',
     'Your expert completes papers, research method assignments, discussion posts, and quizzes in APA format, quality-reviewed before submission.'],
    ['research papers', 'APA formatting', 'statistics for psychology', 'case studies', 'discussion posts'],
    [{ q: 'Do you write psychology papers in APA?', a: 'Yes. All psychology papers are written in APA 7th edition with correct citations and references.' },
     { q: 'Can you handle psychology statistics?', a: 'Yes, we complete statistics assignments in SPSS and other tools with clear interpretation.' },
     { q: 'Which psychology courses do you cover?', a: 'Developmental, cognitive, abnormal, social, and research methods.' },
     { q: 'Is the work original?', a: 'Yes — every paper is written from scratch and checked for originality.' }]),
  'business-management-help': makeSubject('business-management-help', 'Business Management', 'business homework help, do my mba class, management assignment help',
    'Case studies, strategy reports, and full MBA courses handled by business experts who deliver polished, well-argued work matched to your rubric and deadlines.',
    ['Business and MBA programs demand analysis, writing, and real-world application. EduPilotHelp provides business management help from experts with corporate and MBA backgrounds.',
     'Your expert completes case studies, strategy reports, and discussion posts with clear frameworks and professional writing, quality-reviewed before submission.'],
    ['case study analysis', 'strategic management', 'organizational behavior', 'operations management', 'business plans'],
    [{ q: 'Can you write MBA case studies?', a: 'Yes. Our experts write structured case analyses using recognized frameworks and professional business writing.' },
     { q: 'Which business courses do you cover?', a: 'Strategy, organizational behavior, operations, HR, and general management.' },
     { q: 'Can you handle a full MBA course?', a: 'Yes, from weekly discussions to capstone projects, to your target grade.' },
     { q: 'Is the work original?', a: 'Yes — every deliverable is written from scratch and checked for originality.' }]),
  'marketing-help': makeSubject('marketing-help', 'Marketing', 'marketing homework help, do my marketing class, marketing plan help',
    'Marketing plans, campaign analyses, and digital marketing coursework created by marketing experts with strong strategy and clear, persuasive writing.',
    ['Marketing rewards strategy plus polished communication. EduPilotHelp provides marketing help from experts across digital marketing, consumer behavior, and brand strategy.',
     'Your expert completes marketing plans, SWOT and campaign analyses, and discussion posts with sound strategy and professional writing.'],
    ['marketing plans', 'consumer behavior', 'digital marketing', 'brand strategy', 'campaign analysis'],
    [{ q: 'Can you write a full marketing plan?', a: 'Yes. Our experts write complete marketing plans with situation analysis, strategy, and tactics.' },
     { q: 'Do you cover digital marketing?', a: 'Yes, including SEO, social media, content, and analytics coursework.' },
     { q: 'Which marketing courses do you cover?', a: 'Principles of marketing, consumer behavior, digital marketing, and brand management.' },
     { q: 'Can you take my whole marketing class?', a: 'Yes, from weekly assignments to the final project.' }]),
  'english-help': makeSubject('english-help', 'English', 'english homework help, do my english class, essay writing help',
    'Essays, literary analyses, and full English courses written by expert writers with strong arguments, correct citations, and polished prose — delivered on time.',
    ['English courses hinge on writing quality, close reading, and correct citation. EduPilotHelp provides English help from expert writers across composition and literature.',
     'Your expert writes essays, literary analyses, and discussion posts with clear arguments and correct MLA or APA formatting, quality-reviewed before submission.'],
    ['argumentative essays', 'literary analysis', 'research papers', 'rhetoric and composition', 'discussion posts'],
    [{ q: 'Are the essays original?', a: 'Yes. Every essay is written from scratch and checked for originality before delivery.' },
     { q: 'Which citation styles do you use?', a: 'MLA, APA, Chicago, and Harvard — whatever your instructor requires.' },
     { q: 'Which English courses do you cover?', a: 'Composition, rhetoric, American and British literature, and creative writing.' },
     { q: 'Can you match my writing style?', a: 'Yes — share a past essay and we can mirror your voice.' }]),
  'law-help': makeSubject('law-help', 'Law', 'law homework help, do my law class, legal writing help',
    'Case briefs, legal memos, and law coursework written by legal experts with correct citations, sound analysis, and clear legal writing — delivered on time.',
    ['Law programs demand precise reasoning, IRAC structure, and correct citation. EduPilotHelp provides law help from experts across contracts, torts, criminal, and business law.',
     'Your expert completes case briefs, legal memos, and essays using IRAC and proper Bluebook or required citation, quality-reviewed before submission.'],
    ['case briefs', 'legal memos', 'IRAC essays', 'contracts and torts', 'business and criminal law'],
    [{ q: 'Can you write case briefs and legal memos?', a: 'Yes. Our experts write case briefs and memos using IRAC structure and correct legal citation.' },
     { q: 'Which law courses do you cover?', a: 'Contracts, torts, criminal law, constitutional law, and business law.' },
     { q: 'Do you use correct legal citation?', a: 'Yes, including Bluebook or your required citation format.' },
     { q: 'Is the work confidential and original?', a: 'Yes — written from scratch, checked for originality, and kept fully confidential.' }]),
};

export const SUBJECT_SLUGS = Object.keys(SUBJECT_PAGES);
